title: Seidi's personal website
logo: /assets/img/self.jpeg
description: Hi, welcome!
show_downloads: false
google_analytics: https://scholar.google.com.br/citations?user=6QUE0LIAAAAJ&hl=pt-BR
theme: jekyll-theme-minimal
author: Seidi
github: [metadata]
