title: Seidi Oyamada
logo: /assets/img/self.jpeg
description: Hi, welcome to my blog!
show_downloads: false
google_analytics: https://scholar.google.com.br/citations?user=6QUE0LIAAAAJ&hl=pt-BR
theme: jekyll-theme-minimal
author: Seidi
